### ISSUE TITLE
Create Dock Class and Table

### ISSUE THREAD

**Issue by sunniraleigh** [epartakki/valetbike#11]
Create a `Dock` class and table with the following variables:

- Address (public)
- Bikes (public)
- Total slots (public)
- Available bikes (public)

**Task is complete when:**

- [ ] A table is added to the database to store Docks
- [ ] The `Dock` class is added to the app
- [ ] Changes are committed and pushed to the repo
