### ISSUE TITLE
Create PaymentPlan Class and Table

### ISSUE THREAD

**Issue by sunniraleigh** [epartakki/valetbike#12]
Create a `PaymentPlan` class and table with the following variables:

- Plan name (private)
- Starting rate (private)
- Hourly rate (private)
- Discounts (protected/limited)

**Task is complete when:**

- [ ] A table is added to the database to store information about PaymentPlans
- [ ] A `PaymentPlan` class is added to the app
- [ ] Changes are committed and pushed to the repo
