### ISSUE TITLE
Create Payment Class and Table

### ISSUE THREAD

**Issue by sunniraleigh** [epartakki/valetbike#14]
Create a `Payment` class and table with the following variables:

- Payment ID (private)
- Payment method (private)
- Payment plan (private)
- Payment dates (private)
- Payment amounts (private)

**Task is complete when:**

- [ ] A table is added to the database to store Payments information
- [ ] A `Payment` class is added to the app
- [ ] Changes are committed and pushed to the repo
