### ISSUE TITLE
Create Bike Table & CRUD Methods

### ISSUE THREAD

**Issue by sunniraleigh** [epartakki/valetbike#18]
Create a `Bike` table to the database and corresponding CRUD methods:

-`AddBike()`: public method
-`RemoveBike()`: public method
-`UpdateBikeInfo()`: public method

Should be done after or in tandem with #16 and #17.

**Task is complete when:**

- [ ] A table is added to the database to store `Bike` information
- [ ] Methods are added to the app
- [ ] Changes are committed and pushed to the repo
