### ISSUE TITLE
Create Map

### ISSUE THREAD

**Issue by sunniraleigh** [epartakki/valetbike#19]
Research Google Maps API to understand how to implement it. Create an interactive map visualization that allows users to view the following information:

- Docks (public)
- Available bikes (public)
- Available slots (public
- User location (private)

**Task is complete when:**

- [ ] Google Maps API is researched
- [ ] Google Maps is implemented on the app
- [ ] Map displays above information
- [ ] Changes are committed and pushed to the repo
