### ISSUE TITLE
Backend: Setup Database

### ISSUE THREAD

**Issue by sunniraleigh** [epartakki/valetbike#28]
Decide on a hosting service for the database. Set up connections to that locally on everyone's computers.

**Task is complete when:**

- [ ] Database hosting service is research
- [ ] Database hosting service is decided on
- [ ] Database instructions are shared with team
- [ ] @sunniraleigh has the db setup
- [ ] @kvangreen has the db setup
- [ ] @amarrap has the db setup
- [ ] @epartakki has the db setup
- [ ] @luciebrock has the db setup

**Comment by sunniraleigh** [comment]
[https://www.beekeeperstudio.io/](https://www.beekeeperstudio.io/)

**Comment by sunniraleigh** [comment]
https://dbdiagram.io/d/6242066cbed6183873133484
