### ISSUE TITLE
Establish Github Workflow

### ISSUE THREAD

**Issue by sunniraleigh** [epartakki/valetbike#29]
Agree on a standard Github workflow (i.e. branches, pull requests).

**Task is complete when:**

- [x] Team meats on Monday (3/21/22) to ensure:
     - [x] Repo works on everyone's local machine
     - [x] Team members understand how branches and pull requests work

**Comment by sunniraleigh** [comment]
### Steps for setting up git connection on local repo and creating your own branch

**1. Navigate to the directory you would like valetbike to exist in, clone repository from Github, and navigate to valetbike repository**

```
cd desired_directory
git clone https://github.com/epartakki/valetbike.git
cd valetbike
```

**2. check git status (all files up to date and being tracked)**

`git status`

output: 
```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

**3. create a branch**

`git branch _your_branch_name_`

**4. switch to your branch**

`git checkout _your_branch_name_`

**Comment by epartakki** [comment]
https://about.gitlab.com/images/press/git-cheat-sheet.pdf

**Comment by luciebrock** [comment]
coming back to this because its so epic
