### ISSUE TITLE
System Diagrams

### ISSUE THREAD

**Issue by sunniraleigh** [epartakki/valetbike#3]
Draw (either by hand or using a digital tool) a comprehensive set of diagrams for the system you propose to build this semester. This visual overview should cover the three key aspects of the system listed below. To do so, you should prepare to leverage three different styles of diagramming: class diagrams, activity diagrams (aka flow charts), and front-end wireframes. Remember to think in terms of the Model View Controller pattern as you map out your proposed system.

- Data models: what information will the system store and how will it be organized?
- Component interaction: how will the app control the flow between its own components and communicate with external providers (e.g. payment processor, mapping service, social media)?
- User views: how will the key screens of the application be laid out?

**Task is complete when:**

- [x] Data model class diagram is complete
- [x] Component interaction activity diagram is complete
- [x] User view front-end wireframe is complete
- [x] Diagrams are added to groupf-a3.pdf
