### ISSUE TITLE
Product Backlog

### ISSUE THREAD

**Issue by sunniraleigh** [epartakki/valetbike#4]
First, agree on a tool to manage your product backlog (e.g. GitHub projects, Trello, Pivotal Tracker, Asana, Google Docs/Sheets, a physical Kanban board with Post-It notes). Then, using your proposed system diagrams, define a week's worth of feature stories that you will tackle in your first sprint. Teams should recall that each member is expected to devote 6-9 hours per week towards your project. Stories in your backlog should: follow the descriptive format discussed in class, include a time estimate in the 1-2-4-8 point/hour system, and be assigned to a particular team member. Once you've populated your backlog, take screenshots or photos showing the details.

**Task is complete when:**

- [x] Tool is decided on
- [x] Backlog is populated with a week's worth of tasks
- [x] Screenshots of the backlog are added to groupf-a3.pdf
