### ISSUE TITLE
Create User Table & User CRUD

### ISSUE THREAD

**Issue by sunniraleigh** [epartakki/valetbike#7]
Using Mysql, Ruby and Rails create a table to store user information and the following CRUD methods:

- `CreateAccount()` : public method
- `DeleteAccount()` : private method

**Task is complete when:**

- [ ] The User table is added to the database
- [ ] The methods are added to the app
- [ ] Changes are committed to the repo
