### ISSUE TITLE
Create Account Table & Methods

### ISSUE THREAD

**Issue by sunniraleigh** [epartakki/valetbike#8]
Create a table to store User Accounts and an `Account` class. Should be connected to User Database and `User` class. Create the following methods:

- `Login()` : public method
- `Signup()` : public method

**Task is complete when:**

- [ ] Account table is created in the database
- [ ] Account class is added to the app
- [ ] Account methods are added to the app
- [ ] Changes are committed and pushed to the repo
