### ISSUE TITLE
Create Ride Class and Table

### ISSUE THREAD

**Issue by sunniraleigh** [epartakki/valetbike#9]
Create a `Ride` class and table with the following variables:

- Bike ID (private)
- Start time (public)
- End time (public)
- Duration (public)
- Payment rate (public)
- Total cost (public)
- Starting dock (public)
- Ending dock (public)
- Distance (public)

**Task is complete when:**

- [ ] A table is added to the database to store Rides information
- [ ] `Ride` class is added to the app
- [ ] Changes are committed and pushed to the repo
